spring:

  jackson:
    default-property-inclusion: non_null

  security:
    user:
      name: admin
      password: password

security:
  oauth2:
    client:
      client-id: clientId
      client-secret: clientSecret
      access-token-uri: http://localhost:6969/oauth/token
      user-authorization-uri: http://localhost:6969/oauth/authorize

    resource:
      user-info-uri: /me
      prefer-token-info: true
      jwk.key-set-uri: /token_keys
server:
  port: 6969

---
# No Spring Cloud Infrastructure is needed
spring:
  profiles: standalone


# Logging
logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint}
          %clr([${spring.zipkin.service.name:${spring.application.name:-}},){magenta}%clr(%X{X-B3-TraceId:-},){yellow}%clr(%X{X-B3-SpanId:-},){cyan}%clr(,%X{X-Span-Export:-}]){blue}%clr([%8.15t]){cyan}
          %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
