spring:
  profiles:
    - native

  security:
    user:
      name: "gateway"
      password: "password"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      # foo-service
      - id: foo-service
        uri: lb://foo-service
        predicates:
        - Path=/foo/**
        filters:
        - RewritePath=/foo/(?<path>.*), /$\{path}
     # bar-service
      - id: bar-service
        uri: lb://bar-service
        predicates:
        - Path=/bar/**
        filters:
        - RewritePath=/bar/(?<path>.*), /$\{path}


# When using Spring Cloud Discovery, you must be aware that anybody who can query your service registry can obtain the credentials.
eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  # Client
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/

# If Spring Security is on the classpath and no other WebSecurityConfigurerAdapter is present, the actuators are secured by Spring Boot auto-config.
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# Logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

server:
  port: 8080