spring:

  # Security
  security:
    user:
      name: "admin"
      password: "password"
  boot:
    admin:
      discovery:
        ignored-services: admin-service

# When using Spring Cloud Discovery, you must be aware that anybody who can query your service registry can obtain the credentials.
eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

# Logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

server:
  port: 8062