spring:
  # Security
  security:
    user:
      name: "admin"
      password: "password"
  boot:
    admin:
      discovery:
        ignored-services: admin-service

# When using Spring Cloud Discovery, you must be aware that anybody who can query your service registry can obtain the credentials.
eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  # Client
  client:
    region: default
    registryFetchIntervalSeconds: 5

# Logging
logging:
  pattern:
     console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

