spring:

  profiles.include:
      - unsecure

   # Cloud
  cloud:
    hypermedia:
      refresh.initial-delay: 100
      refresh.fixed-delay: 500

  security:
    user:
      name: "bar"
      password: "password"


# When using Spring Cloud Discovery, you must be aware that anybody who can query your service registry can obtain the credentials.
eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  # Client
  client:
    region: default
    registryFetchIntervalSeconds: 5

# If Spring Security is on the classpath and no other WebSecurityConfigurerAdapter is present, the actuators are secured by Spring Boot auto-config.
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# Logging
logging:
  pattern:
     console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org.springframework.cloud.client.hypermedia: DEBUG

server:
  port: 4001