server:
  port: 8082

spring:
  security:
    user:
      name: "bar"
      password: "password"
  profiles:
    active:
      - unsecure
  # Cloud
  cloud:
    hypermedia:
      refresh.initial-delay: 100
      refresh.fixed-delay: 500


# When using Spring Cloud Discovery, you must be aware that anybody who can query your service registry can obtain the credentials.
eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  # Client
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/


# If Spring Security is on the classpath and no other WebSecurityConfigurerAdapter is present, the actuators are secured by Spring Boot auto-config.
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# Logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org.springframework.cloud.client.hypermedia: DEBUG