# ---------------------
# Stages
# ---------------------

stages:
  - Setup
  - Build
  - Tests

# ---------------------
# Setup
# ---------------------

Proxy:
  stage: Setup
  script:
    - git config --global http.proxy http://webpro-sv:8080/
    - git config --global https.proxy http://webpro-sv:8080/
    - git config --global http.sslVerify false
  tags:
    - helsana


# ---------------------
# Build stage jobs
# ---------------------

Build:
  stage: Build
  script:
    - mvn install
  artifacts:
    name: "build-$CI_COMMIT_REF_NAME"
    paths:
      - target/
  tags:
    - helsana

# ---------------------
# Test stage jobs
# ---------------------

Unit Tests:
  stage: Tests
  script:
    - mvn -P \!developer-machine-not-helsana -Prelease-dry-run test
  dependencies:
    - "Build"
  tags:
    - helsana
